### ISSUE TITLE
Nice Implementation! 

### ISSUE THREAD

**Issue by SirRob1997** [zhengxxn/adaptive-knn-mt#3]
Really cool implementation, a lot cleaner and better integrated within fairseq than the implementation provided by the original knn-MT work! 

If one would want to adapt this to the multilingual task as well, do you have an idea how the `forward_and_get_hidden_state_step` method would look like and what would need to change in the `save_datastore.py` script?

**Comment by zhengxxn** [comment]
I think that the main difference between multilingual translation task and single language pair translation task is that prepend `language id` instead of `BOS/EOS`(fairseq use EOS actually) for each target sentence, so it can be easy extend to multilingual task in two ways:

- append `language token` in raw multilingual data manually, and disable `--prepend-bos/eos` in target side, and regard it as a `translation` task.
- use `multilingual_translation` task, and it will automatically replace the `bos/eos` with `language id`. You could copy the `forward_and_get_hidden_state_step` function to the task, and i think there is nothing else to append.

While in `multilingual translation` task, it may use multiple datasets to build datastore, so the datastore size should be set as the sum of all datasets. and i think nothing else should be changed in `save_datastore.py`

**Comment by SirRob1997** [comment]
Yup that's what I thought as well! Thanks a lot =) Great work!
